### ISSUE TITLE
List textures

### ISSUE THREAD

**Issue by prifio** [hunt-the-wumpus/HuntTheWumpus#11]
Текстуры комнат. И опасностей. Было бы хорошо, если бы у нас были разные текстуры комнат.
Мосты/двери. Вроде готовы, но не добавлены.
Background для интерфеиса. Надо как-то красиво заполнить центр. 
Меню. Мы будем его делать текстурой, или рисовать программно?? По крайней мере, лого надо бы текстурой(прототип есть).
Фон для Win/Loos.
Я конечно, что-то забыл. Напишите это. И напишите, что готовы взять или уже сделали

**Comment by prifio** [comment]
Я попробую сделать background

**Comment by JaleChaki** [comment]
Толя, смотри у нас текстуры комнат плохие, потому что там немного (много) не сходятся границы

**Comment by prifio** [comment]
Осталось-win и текстуру вампуса. И я очень рад
