### ISSUE TITLE
Polishing UX

### ISSUE THREAD

**Issue by vors** [hunt-the-wumpus/HuntTheWumpus#16]
- [x] На экране выбора пещеры, заменить "Enter your seed" на "Pick a cave or enter your seed"
- [x] Выводить баннер когда мы собираем монеты (во время анимации движения)
- [x] Добавить текст "Enter your name" на экран ввода имени в конце игры
- [x] Выводить подсказку про управление в начале в виде баннера: Left click to move, right click to shoot arrow, Esc to open menu  ( @JaleChaki  )
- [x] Нужен баннер когда вампус убегает ( @prifio  )
- [x] Когда не хватает денег на покупку нужно выводить баннер "Not enough coins (need <n>)"
- [x] Если игрок еще не стрелял ни разу, выводить подсказку про правую кпопку мыши вместе с Smell the wumpus ( @prifio  )
- [x] Добавить выбор сложности в pick cave ( @prifio )
- [x] Walking wampus ( @prifio )
- [x] Перенести все строки в Messages.resx ( @prifio  )
- [x] Прокоментить код ( @prifio )
- [x] Добавить текста в readme

**Comment by prifio** [comment]
- [x] Нажо приукрасить форму. Logo, name, fixSize( @prifio )
- [x] Две ачивки. Аналог снайпера и не разу не проходил МиниИгру ( @sulimgar )
- [x] Bag fix WumpusGoAway ( @prifio )

**Comment by JaleChaki** [comment]
- [x] Перевести на английский все, что написано на русском ( @sulimgar )
