### ISSUE TITLE
Формула для Score

### ISSUE THREAD

**Issue by prifio** [hunt-the-wumpus/HuntTheWumpus#2]
В спецификации есть формула для score. Как по мне-там не оч она хорошая. Довольно странно дают очки. +Мы будем показывать score во время игры, или нет??

**Comment by vors** [comment]
Во время игры я думаю не стоит. Согласен - алгоритм там странный.
Как вариант можно добавить два скора и посмотреть как они будут себя вести.
Плюс если у нас есть ачивки, то можно через них многие вещи выразить а score оставить по спецификации.

**Comment by vors** [comment]
Мы сошлись на том что score будет по спецификации + ачивки
