### ISSUE TITLE
Achivements

### ISSUE THREAD

**Issue by vors** [hunt-the-wumpus/HuntTheWumpus#3]
Нам нужен список achievements

**Comment by JaleChaki** [comment]
По просьбе Prifio кидаю список ачивок
- [x] Быстрый          - пройти миниигру на 1 уровне сложности потратив меньше 7 секунд
- [x] Реактивный        - пройти миниигру на 2 уровне сложности потратив меньше 7 секунд
- [x] Живчик                - пройти миниигру на 3 уровне сложности потратив меньше 7 секунд
- [x] Точный                - набрать в миниигре на 1 уровне сложности 500 очков, нарисовав только 1 фигуру
- [x] //тут название и описание аналогично для второго уровня
- [x] Снайпер              - набрать в миниигре на 3 уровне сложности 500 очков, нарисовав только 1 фигуру
- [ ] Исследователь      - побывать во всех комнатах пещеры
- [ ] Потомок Гамильтона  - пройти через все комнаты, побывав в каждой только 1 раз
- [ ] Шаг в бездну      - исследовать 25 комнат
- [ ] Лучник                - получить 5 стрел
- [ ] Охотник              - получить 15 стрел
- [ ] Воин                - получить 25 стрел

**Comment by vors** [comment]
Нужно добавить achivements с картинками в README.md

**Comment by muroming** [comment]
Всё добавлено
