### ISSUE TITLE
Switch to XUnit framework

### ISSUE THREAD

**Issue by vors** [hunt-the-wumpus/HuntTheWumpus#4]
Default test framework in Visual Studio sporadically fails on the graphics tests 

For example, for 5e872c89 there are two builds
https://ci.appveyor.com/project/HuntTheWumpus/huntthewumpus/build/1.0.40 (failed)
https://ci.appveyor.com/project/HuntTheWumpus/huntthewumpus/build/1.0.43 (ok)

We probably need to switch to XUnit to avoid it.

**Comment by prifio** [comment]
Now, I add xUnit to project. 
Thanks for help with install.
