### ISSUE TITLE
Seed for Map generator

### ISSUE THREAD

**Issue by prifio** [hunt-the-wumpus/HuntTheWumpus#7]
If I create 5 Map for PickCave then all maps are equal. Every map create System.Random. If time create ~~ then seed for System.Random are equal. 
And, if player can enter seed, it's really good
Control create System.Random too for pick hint. I think, I shouldn't merge seed for map and for Control.

P.S(ужасный мой английский)

**Comment by vors** [comment]
So in general, it's a good idea to have a one Random generator.
You can put it in some utility class and the replace all calls to a static method call.
That way, you will get a consistent random across all the app.

**Comment by prifio** [comment]
Now, I add Utily Class with method Next for generate RandomInt. Other should use this method.
And, Swap move to Utily class
